from typing import Any, Dict, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from app.models.job import JobData

class CareerDocsData(BaseModel):
    """
    Model containing resume and letter
    """
    resume_optimized: Optional[dict[str, Any]] = None
    cover_letter: Optional[dict[str, Any]] = None

class JobResponse(JobData):
    style: Optional[str] = None
    sent: Optional[bool] = None
    gen_cv: Optional[bool] = None

class PendingJobResponse(JobResponse):
    timestamp: datetime = None

class ApplyContent(BaseModel):
    jobs: Dict[str, JobResponse]

class PendingContent(BaseModel):
    jobs: Dict[str, PendingJobResponse]
    
class DetailedJobData(CareerDocsData):
    job_info: JobData
    style: Optional[str] = None
    sent: Optional[bool] = None
    gen_cv: Optional[bool] = None

class CareerDocsResponse(BaseModel):
    """
    Model for applications generated by Career Docs
    """
    user_id: int
    mongo_id: str
    applications: dict[str, CareerDocsData]
    success: bool

class JobsToApplyInfo(BaseModel):
    user_id: int
    jobs: list[dict]
    mongo_id: str
    style: str | None = None
    cv_id: str | None = None
