from typing import Any, Dict, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from app.models.job import JobData

class ApplyContent(BaseModel):
    jobs: Dict[str, JobData]

class CareerDocsData(BaseModel):
    """
    Model containing resume and letter
    """
    resume_optimized: Optional[dict[str, Any]] = None
    cover_letter: Optional[dict[str, Any]] = None

class DetailedJobData(JobData, CareerDocsData): #python's got double inheritance, yaaay
    pass

class CareerDocsResponse(BaseModel):
    """
    Model for applications generated by Career Docs
    """
    user_id: int
    mongo_id: str
    applications: dict[str, CareerDocsData]
    success: bool

class JobsToApplyInfo(BaseModel):
    user_id: int
    jobs: list[dict]
    mongo_id: str
    cv_id: str | None = None
